import os

# Protein zəncirinin kütləsini amin turşularının kütlə cədvəlinə əsasən hesablayırıq
# Compute the mass of a protein sequence using the monoisotopic mass table

protein = "MAFGNYYWQMIRPTMCREFWIVLTFNASGKQPSCMNTWTNQCENAHSGWRFDGDLGLVVYHSFDRLPIKWMFIQLYSDDAVLMSISSMIMAGYRGKVSSCIDHESYNFQLTQHCAQFVWFDNGDMCSFVCVWIRDEDCMNHRAINDAFTRMSNWESIWGQDMEWTYSQIDISYVEFTDSYTLEGESTMPWHFYTEMLQQDGAKHGRKSGTGVQGEQLEDRAPYELTMDMRQPNEFHFWDIKERQYSGFYCPLYHNIRSKQYVHASDEVEAANATLNGKSITWQQGGADTRSFQSWMMQVEEADEGDWVSYTNSRAKKNDSQYYNMWYYQTVFWITAIMHNLMVYGFCFYDSNPPPHRFLRKYKTCLTKCCPGCFEANETMNPWHHGRGHICYLRNMWYMSHEGQFEVKPQCNYDYRSLSNNGIQTRYWDPKHWIHHIPFYWSIGLYVTLVCTNEIRCPNPEAPEEENFVDVKLKPKMGYTRDGNWHIAYVPAFTQFRWCGSVPHENNKNGHCDWLPMYCEEAHCHRHWDQKECSNRECLWQYPPPDEIYYVMNFNICWNSKSIYHRFFAITYLYICVSGCIICNRMFQSPFIMMNAHYWFEEQSGVKSDAECGITPRSGRMYTHFSKDLAMRSQSVLINVIQEMRLHPFLDQIVADYMKNEDIYQLMDNNAPKKRMYVDRHWKNWNNTNWTVTWCGPMHPEECWIVVCYHKVNSHSMEIAVSLHSNRACMSIRCNDMTFCNSWPQTKDFTATKRRYEMWIDQFWTFWGSGIVDGQKQTIPRDHYDMVHQHMDNDNKAGWCSFMHMTFRYCEWRSHMWMDRGHNETIDEKRFGIGNSNMYPPGKKLIMNHFLKGRIIVGVRHKTVSRFEMHMTYVPQFSCCTASPQEY"

mass_table = {
    'A': 71.03711, 'C': 103.00919, 'D': 115.02694, 'E': 129.04259,
    'F': 147.06841, 'G': 57.02146, 'H': 137.05891, 'I': 113.08406,
    'K': 128.09496, 'L': 113.08406, 'M': 131.04049, 'N': 114.04293,
    'P': 97.05276, 'Q': 128.05858, 'R': 156.10111, 'S': 87.03203,
    'T': 101.04768, 'V': 99.06841, 'W': 186.07931, 'Y': 163.06333
}

# Hər amin turşusunun kütləsini cəmləyirik
# Sum the masses of all amino acids in the protein sequence
total_mass = sum(mass_table[aa] for aa in protein if aa in mass_table)
print(f"Total Mass: {total_mass:.5f}")

# Nəticəni output.txt faylına qeyd edirik
# Write the total mass to output.txt
with open("output.txt", "w") as out:
    out.write(f"{total_mass:.5f}\n")
